export const navigatorLinks = {
    SpLogin: 'SpLogin',
    FacilityManaging:'FacilityManaging',
    ContactUs: 'ContactUs',
    Main: 'Main',
    FacilityDetails: 'FacilityDetails',
    Costs: 'Costs',
    Suggestion: 'Suggestion',
    NoticBoard: 'NoticBoard',
    Units: 'Units',
    UnitsCreate: 'UnitsCreate',
    AddCost: 'AddCost',
    AddUnit: 'AddUnit',
    Lobby:'Lobby',
    AboutMonta: 'AboutMonta',
    AddSans: 'AddSans',
    Rules: 'Rules',
    Profile: 'Profile',
    Survey: 'Survey',
    Setting:'Setting',
    Payment: 'Payment',
    Period: 'Period',
    Announcement: 'Announcement',
    AnnouncementEdit: 'AnnouncementEdit',
    Years:'Years',
    IppCharge: 'IppCharge',
    PayAnnounce: 'PayAnnounce',
    Transaction: 'Transaction',
    FirstUserBalance:'FirstUserBalance',
    PayAdmin:'PayAdmin',
    User2UnitAssignment:'User2UnitAssignment',
    Account:'Account',
    AddAccount: 'AddAccount',
    AccountDisabled: 'AccountDisabled',
    PayResult:'PayResult',
    Facility: 'facility/Facility',
    AddFacility: 'facility/AddFacility',
    FacilityDisabled: 'facility/FacilityDisabled',
    AddSetting: 'AddSetting',
    AddAnnouncement: 'AddAnnouncement',
    ManualPay: 'ManualPay',
    MyUnit: 'MyUnit',
    AddMessage: 'AddMessage',
    AddSuggestion: 'AddSuggestion',
    AddRule: 'AddRule',
    AddSurvey: 'AddSurvey',
    NearMe:'NearMe',
    AboutApplication: 'AboutApplication',
    AboutUs: 'AboutUs',
    Cars: 'car/Cars',
    AddCar: 'car/AddCar',
    CarsUnit: 'car/CarsUnit',
    AllCar: 'car/AllCar',
    GuestsList:'car/GuestsList',

    AllTransaction: 'AllTransaction',
    AllTransactionOfDate: 'AllTransactionOfDate',

    Magazzino: 'rent/Magazzino',
    Parking: 'rent/Parking',

    RentCreate:'RentCreate',
    Renting:'Renting',
    AddFacilityAdditional: 'facility/AddFacilityAdditional',
    FacilityFilter: 'facility/FacilityFilter',
    AddSchedule:'facility/AddSchedule',
    ScheduleList: 'facility/ScheduleList',
    FacilityFilterList: 'facility/FacilityFilterList',
    FacilityReservation:'facility/FacilityReservation',
    FacilityForReserve: 'facility/FacilityForReserve',
    MyReserves:'facility/MyReserves',
    Wallet: 'Wallet',
    ScheduleReserved: 'ScheduleReserved',
    UserScheduleReserved: 'UserScheduleReserved',

    Buildings:'Buildings',
    BuildingContact:'BuildingContact',
    Role:'Role',
    User:'Users',

};